[tool.black]
line-length = 88
target-version = ['py39']
include = '\.py$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | __pycache__
  | notebooks
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 88
extend-ignore = [
    "E203",  # конфликт с black
    "W503"   # конфликт с black
]
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv"
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]

